# Generated by Django 2.0.13 on 2021-01-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=30, verbose_name='nickname'),
        ),
    ]
