# Generated by Django 2.0.13 on 2021-01-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('matched', 'matched'), ('quit', 'quit')], max_length=50, verbose_name='status'),
        ),
    ]
