# Generated by Django 2.0.13 on 2021-01-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210124_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('matched', 'matched'), ('closed', 'closed')], max_length=50, verbose_name='status'),
        ),
    ]
