# Generated by Django 2.0.13 on 2021-01-28 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20210124_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomparticipant',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='roomparticipant',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='user_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_user_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='user_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_user_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RoomParticipant',
        ),
    ]
