# Generated by Django 2.0.13 on 2021-01-29 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20210129_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user_2',
        ),
        migrations.AddField(
            model_name='room',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
